### ISSUE TITLE
Discover Milan is about 22% slower than Cascade Lake; with Intel 2021.10.0 instead of 2021.6.0 on Milan, memory use is 2x as much

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1030]
**Describe the bug**

This is https://github.com/JCSDA/spack-stack/issues/1011#issuecomment-2002715016, the last comment in issue #1011:

Here is a poor man's comparison of three different experiments, where the large variational task (18 nodes, 12 tasks per node (due to memory limitations on scu16, maybe potential for optimization on scu17)) ran twice. Note: I used the I_MPI settings from @mathomp4 for SCU17.

The takeaways:
- No difference in runtime between Intel 2021.10.0 and 2021.6.0 on SCU17, but a **huge** difference in memory footprint!
- SCU17 is about 22% slower than SCU16

```
SCU17 with 2021.10.0

OOPS_STATS Run end - Runtime:   1901.65 sec,  Memory: total:  3577.86 Gb, per task: min =    15.42 Gb, max =    21.33 Gb

OOPS_STATS Run end - Runtime:   1613.91 sec,  Memory: total:  3292.10 Gb, per task: min =    14.12 Gb, max =    20.47 Gb


SCU17 with 2021.6.0

OOPS_STATS Run end - Runtime:   2081.32 sec,  Memory: total:  1577.36 Gb, per task: min =     6.24 Gb, max =    11.75 Gb

OOPS_STATS Run end - Runtime:   1592.81 sec,  Memory: total:  1402.77 Gb, per task: min =     5.48 Gb, max =    11.59 Gb


SCU16 with 2021.5.0

OOPS_STATS Run end - Runtime:   1638.15 sec,  Memory: total:  1613.46 Gb, per task: min =     6.43 Gb, max =    11.81 Gb

OOPS_STATS Run end - Runtime:   1308.62 sec,  Memory: total:  1435.14 Gb, per task: min =     5.59 Gb, max =    11.83 Gb
```

I am going to close this issue as resolved, because the factor-of-many difference in runtime we saw initially is addressed by the I_MPI settings. But I'll open another issue for the 22% runtime difference SCU16/17 and factor of 2 memory increase on SCU17 with 2021.10.0 vs 2021.6.0.

**To Reproduce**
Run `skylab-aero-weather` experiment and look at `variational` task on SCU16 (Cascade Lake) and SCU17 (Milan) with Intel - see above for versions.

**Expected behavior**
1. It is not clear to me if the 22% increase in runtime is expected or not (after all, using an Intel compiled executable on an AMD CPU vs an Intel CPU).

2. Certainly, the factor 2 memory use with the newer Intel version is not expected.

**System:**
See above

**Additional context**
n/a

**Comment by climbfuji** [comment]
@mathomp4 @dooruk FYI

**Comment by mathomp4** [comment]
Well that is interesting. I'm going to ping @tclune and @atrayano on this. I've only done small tests with Intel 2021.11 so far, and I'll do some more tomorrow with GEOS.

We know using Jemalloc can help with memory usage, but I'm not sure it can help with a 2x memory increase!

**Comment by mathomp4** [comment]
Well, I did some tests with GEOS today. C360, 1day, and ran 3 of them. Each had the same number of processes. The runs were:

* Intel 2021.6.0 + Intel MPI 2021.6.0 + SLES12
* Intel 2021.6.0 + Open MPI 4.1.6 + SLES15
* Intel 2021.11.0 + Intel MPI 2021.11.0 + SLES15

So not exactly apples-to-apples, but not bad.

As for timings I saw (for model throughput, days/day):

| Run | T'put 1 | T'put 2 | T'put 3 |
| --- | --- | --- | --- |
| 2021.6 SLES12 | 109.07 | 115.90 | 117.67 |
| 2021.6 SLES15 | 95.57 | 96.55 | 96.83 |
| 2021.11 SLES15 | 96.64 | 100.10 | 102.44 |

So about 15-20% slowdown on SLES 15. But I suppose the Cascade Lakes are 2.4 GHz and the Milans are 2.0 GHz so you might expect ~20% slowdown.

As for memory use, I do see more on Milan, but not crazy more. Here the top image is Intel 2021.6 + SLES12, then Intel 2021.6 + SLES15, and then Intel 2021.11 + SLES 15:

![test](https://github.com/JCSDA/spack-stack/assets/2982494/f9647933-de51-45d4-8046-469a96cfbc26)

So, at their worst we see 48% on SLES12 and about 56% on SLES15. We run with 45 tasks per node on SLES12 (192 GB) and 126 tasks per node on SLES15 (512 GB) so that is 2.05 GB/process on SLES12 and 2.28 GB/process on SLES15.

**Comment by mathomp4** [comment]
@climbfuji One thought I just had. I know with Intel 2024.0 on discover, you get `icx` and `icpx` as your C and C++ compilers.

If OOPS is a C++ code, is it possible `icpx` is sneaking in and (for some reason) causing a memory increase?

**Comment by climbfuji** [comment]
@mathomp4 Good idea, but we still use the classic compilers at the moment (https://github.com/JCSDA/spack-stack/blob/b22234c5d61173650ffcf88bc28fe3a0970df645/configs/sites/discover-scu17/compilers.yaml#L5)

**Comment by eap** [comment]
Reviewing backlog today and none of us are sure if this issue still need to be tracked; is the current performance acceptable or is there specific debugging and/or optimization that needs to be done to address this?

**Comment by Dooruk** [comment]
@eap, thanks for following up on this. It looks like system hardware difference and there is not much we can do so you can close this for now.

Dom switched the Intel compiler version from `2021.10.0` to `2021.6.0` and that provided a significant performance increase, see the first comment above. If NCCS or GEOS see another performance bump with a more recent compiler version, we could test that otherwise I'm content with what we have. 

Not sure if JCSDA folks are using Milan nodes on Discover (I can't seem to tag them here?) and have any complaints?
