### ISSUE TITLE
Create NetCDF meta-module

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#12]
Rather than loading NetCDF-C and -Fortran individually, (and already depend on each other) it would be nice to have a `netcdf` module that encapsulates both. I think this might be possible using a `BundlePackage` of `netcdf-c` and `netcdf-fortran`.

Otherwise, they'll have to be separate or externally created.

**Comment by climbfuji** [comment]
I actually like the fact that there is no "netcdf" package (and module), because it shields us from a lot of the problems with conflicting netcdf packages in the default module hierarchy on some of the HPC systems.

**Comment by climbfuji** [comment]
@kgerheiser I would like to come back to this. I tested the two separate modules on gaea (static build) and it works fine.

**Comment by climbfuji** [comment]
@kgerheiser since we don't really need the netCDF meta module, can we close this issue?

**Comment by climbfuji** [comment]
I am going to close this issue, because the netcdf-c, netcdf-fortran, netcdf-cxx4 modules work just fine and shield us from the default modules installed by the sysadmins on the various HPC systems. Please reopen if you disagree

**Comment by ulmononian** [comment]
@climbfuji @Hang-Lei-NOAA rather than opening a new issue/discussion, i thought i would touch back on this to ask about a netCDF meta-module. is there an approach for loading, for example, netcdf@4.7.4 as in https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_common? i have installed netcdf-c@4.7.4 & netcdf-fortran@4.5.4 in my ufw-wm spack environment, but it would be ideal for users to be able to utilize the existing ufs_common module file and i am not sure how to set this up. will having netcdf-c@4.7.4 & netcdf-fortran@4.5.4  satisfy the need for netcdf@4.7.4, or is something more required ?

**Comment by climbfuji** [comment]
I am against a netcdf meta module. This impacts the ability to use different combinations of netcdf-c and netcdf-fortran. Simply load two modules instead of one. `ufs_common` can be updated when moving from `hpc-stack` to `spack-stack`.

**Comment by ulmononian** [comment]
@climbfuji that is very reasonable. as long as loading netcdf-c and netcdf-fortran fully serves the functionality of the unified netcdf module, this sounds good.

**Comment by climbfuji** [comment]
At least I am not having any problems so far with using those two modules separately.
