### ISSUE TITLE
Need to capture dependency of mapl on ESMF?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#15]
mapl depends on the ESMF version. In hpc-stack, we capture this by append the ESMF version to the mapl version. This is, however, somewhat inconsistent, because we don't do this for any other package that depends on some package in the stack (i.e. we don't add the netcdf version to any of the packages, even though many of the packages depend on it).

Should we try to be more consistent and drop the ESMF dependency information from the mapl install/module name? Simply roll out an entirely new env if a new mapl/esmf combination is required?

Or are ESMF and map outliers that change a lot more often than netcdf such that it makes sense to add this hierarchy information? We should be able to do this with spack.

**Comment by kgerheiser** [comment]
This is a good question that I've been pondering, but don't have a good answer for.

The MAPL versioning was added because there was a bug when mixing different versions of ESMF than the one MAPL was built with. I don't know if rolling out a new environment every time a new version of ESMF is ideal, but that depends on our workflow. ESMF is updated semi-regularly and each time that happens it requires a new MAPL.

But I'm also not exactly sure how to handle it in Spack.
