### ISSUE TITLE
Update documentation to include section on using on workstations or HPC systems where it is not installed

### ISSUE THREAD

**Issue by edwardhartnett** [JCSDA/spack-stack#253]
How does a scientist build the UFS on her own linux workstation using spack-stack? (Or does she just use spack directly?)

**Comment by climbfuji** [comment]
> How does a scientist build the UFS on her own linux workstation using spack-stack? (Or does she just use spack directly?)

This documentation is definitely needed, but should not be in the spack-stack repo. It should be in the ufs-weather-model documentation. We did the same for JEDI. spack-stack just builds the prerequisite modules for each of the apps, it's up to the app documentation in my opinion to document how to use it.

**Comment by climbfuji** [comment]
There is currently some information in the spack-stack wiki (where it does not belong). Until the wiki is cleaned up, I will keep this issue open. That kind of documentation, as discussed before (https://github.com/NOAA-EMC/spack-stack/issues/253#issuecomment-1182173052), belongs to the individual applications/models that use spack-stack.

**Comment by climbfuji** [comment]
@edwardhartnett I was going to schedule a meeting with you to go over this, but time is short. Please take a look at https://spack-stack.readthedocs.io/en/latest/Platforms.html#generating-new-site-configs - this describes in detail how to create spack-stack environments on new systems (macOS, Ubuntu, Red Hat).

Regarding documentation for how to build the ufs-weather-model or other UFS components on systems that don't have a pre-configured environment (will not I better say, because right now we don't have any pre-configured spack-stack environments that are used by the UFS by default): this information should go into the relevant UFS documentation, just like JCSDA maintains this documentation in jedi-docs (https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/using/index.html).

If you agree, please close this issue as completed or let us know what is missing. Thanks!

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/419
