### ISSUE TITLE
Create Intel Container Image

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#279]
**Is your feature request related to a problem? Please describe.**
The only container template we have is `docker-ubuntu-gcc-openmpi`. There should be an Intel container as well.

**Describe the solution you'd like**
Create Intel container template based off of https://hub.docker.com/r/intel/oneapi-hpckit

**Comment by climbfuji** [comment]
@kgerheiser I spoke with @mark-a-potts last week. He said that he already built a container using Intel oneAPI (I think he installed the compiler via spack). Let's make sure we don't reinvent the wheel.

Also tagging @mer-a-o for her awareness. Maryam will be working on a clang+gfortran container next, and update the existing gnu container so that it works correctly. So far, I have only built the container, not tried to run anything with it.

**Comment by kgerheiser** [comment]
@climbfuji this is related to that because @mark-a-potts brought it up and I was talking @ulmononian about containers as well.

**Comment by mark-a-potts** [comment]
I currently have a oneapi-based container with spack-stack installed here--docker://noaaepic/ubuntu20.04-spack-stack:latest. That container required manual intervention to build, however. I used spack to install both compilers and MPI because the oneapi-hpckit recipe referenced would not run correctly for me. I am working on a recipe.
