### ISSUE TITLE
Add esmf@8.4.1 and mapl@2.35.2 (replace existing versions in unified env)

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#333]
**Please describe the package or library you would like to add to spack-stack.**
See https://github.com/NOAA-EMC/hpc-stack/issues/485 for more details.

**What applications will be using this package or library?**
UFS

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
Earlier versions of mapl

**Additional context**
n/a

**Will This Package be Needed in a NOAA Operational Application?**
Yes

**WCOSS System Software Request Checklist**

See https://github.com/NOAA-EMC/hpc-stack/issues/485 (if there is no checklist in hpc-stack, then let's ask the requester to add one).

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @mathomp4 @junwang-noaa I started working on this, and quickly realized that we'd be better off waiting for @mathomp4 to finish his PR https://github.com/NOAA-EMC/spack/pull/174. I can add mapl 2.35.2 myself, but it means we'll need to solve conflicts later when merging https://github.com/NOAA-EMC/spack/pull/174. Further, newer mapl versions want `fargparse`, which is not in spack yet (but included in PR 174).

We have a pretty tight timeline for the next release. If @mathomp4 thinks that his PR for our spack fork is ready in the next two days (and won't break anything), then lets get it in. Otherwise we could try to copy the mapl and fargparse changes from this PR and deal with the conflicts later, or abandon the idea and stick with mapl 2.22 for this release. (JEDI doesn't need the new mapl functionality, we are fine with 2.22 and ESMF 8.3.0b09 or 8.4.1).

**Comment by climbfuji** [comment]
> @AlexanderRichert-NOAA @mathomp4 @junwang-noaa I started working on this, and quickly realized that we'd be better off waiting for @mathomp4 to finish his PR [NOAA-EMC/spack#174](https://github.com/NOAA-EMC/spack/pull/174). I can add mapl 2.35.2 myself, but it means we'll need to solve conflicts later when merging [NOAA-EMC/spack#174](https://github.com/NOAA-EMC/spack/pull/174). Further, newer mapl versions want `fargparse`, which is not in spack yet (but included in PR 174).
> 
> We have a pretty tight timeline for the next release. If @mathomp4 thinks that his PR for our spack fork is ready in the next two days (and won't break anything), then lets get it in. Otherwise we could try to copy the mapl and fargparse changes from this PR and deal with the conflicts later, or abandon the idea and stick with mapl 2.22 for this release. (JEDI doesn't need the new mapl functionality, we are fine with 2.22 and ESMF 8.3.0b09 or 8.4.1).

Another option may be to add the missing variant to enable/disable fargparse from @mathomp4's PR and not worry about fargparse for this release. Then solve conflicts later when https://github.com/NOAA-EMC/spack/pull/174 is ready.

**Comment by climbfuji** [comment]
It looks like I am able to build mapl@2.35.2 by turning off the fargparse option. I'll create a draft PR to look at, if that seems to be a safer option than the big PR with all the GEOS packages a day or two before the code freeze, then we may go this route.

**Comment by AlexanderRichert-NOAA** [comment]
Using @mathomp4's draft MAPL package.py and the updated ESMF package.py, I can build the unified stack on hera and successfully build and run the latest UFS with the cpld_control_p8 case (all files match which is impressive!). The only further change was to remove `+pio` and add `+parallelio` for the esmf variants in common/packages.yaml.

@climbfuji Do you want me to do the PRs for this? If you're already deep into it then go ahead but otherwise I'm happy to make the changes (new mapl version+fargparse dep/variant, and esmf and mapl changes in common/packages.yaml).

**Comment by Hang-Lei-NOAA** [comment]
Great job, mapl build has to turn off the fargparse.
and netcdf 4.9.1 on acorn should turn off --disable-libxml2
--disable-byterange
@alex If you can do the PRs ,please do it. I can test it with other cases
of UFS. I have tested the UFS aerosols case with mapl. But the case with
the fully coupled one did not work.

**Comment by climbfuji** [comment]
I think I’ve got it all in my currently open draft PRs, possibly except removing the +pio (please check).

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji Okay great, those look good to me as far as this issue is concerned. And yes, `+pio` will need to get removed in favor of the external pio. Also, can we please change netcdf-c to version 4.9.1 in the same PR? I haven't tested 4.9.0 myself, but apparently there have been problems with it at least w.r.t. to UFS.

@Hang-Lei-NOAA I can add +fismahigh to ufs-weather-model-static/spack.yaml (dap is already disabled, which I believe is what determines libxml2 inclusion).

**Comment by climbfuji** [comment]
There was a bug with 4.9.1, beyond the byterange compiler error, wasn’t it? It didn’t work with the UFS when we first tried, that’s why we went back to 4.9.0.

**Comment by AlexanderRichert-NOAA** [comment]
It worked with 4.9.1 for me on hera just now... @Hang-Lei-NOAA @junwang-noaa which netcdf-c version did we end up landing on?

**Comment by Hang-Lei-NOAA** [comment]
netcdf-c/4.9.1; netcdf-fortran/ 4.6.0 and netcdf-cxx/4.3.1

**Comment by climbfuji** [comment]
netcdf-c@4.9.2 was just released with several bug fixes that might be important or at least of interest to us ... https://github.com/Unidata/netcdf-c/releases/tag/v4.9.2 I really don't like updating to a new version so close cutting release branches, but we can always roll back to 4.9.1 if it's needed, and we did have issues with that version before.

Any strong objections trying that?

**Comment by Hang-Lei-NOAA** [comment]
@climbfuji <https://github.com/climbfuji>   Could you please add both 4.9.1
and 4.9.2 into spack?
Although I also had some issues with 4.9.1, the UFS team will use it for
this upgrade step.

**Comment by climbfuji** [comment]
We need to choose one to build everything with. I can add 4.9.2 to the spack package, so that spack knows about it, but we can only install one. I’ll give it a shot with 4.9.2.

**Comment by AlexanderRichert-NOAA** [comment]
Compiled and ran UFS WM successfully on Hera with 4.9.2 using unified env, so between that and 4.9.0 I'd opt for 4.9.2.

**Comment by climbfuji** [comment]
Thanks @AlexanderRichert-NOAA ! I am trying that version this morning, too.

**Comment by mathomp4** [comment]
Note on the GEOS side (which of course isn't quite ready for spack-stack): Since we are a netCDF-Fortran shop, we'll probably stick with netCDF-C 4.9.0 for the near future. From the announcement:

> Next up, the netCDF team is working on releases for the Fortran and C++ interfaces...

I always wait until I hear from the team that netCDF-Fortran is "good". I mean, I'm sure it does work, but I'm pretty conservative with netCDF. (Meanwhile, ESMF betas galore! 😄 )
