### ISSUE TITLE
nccmp from fork to authoritative spack repo

### ISSUE THREAD

**Issue by aerorahul** [JCSDA/spack-stack#477]
`nccmp` is used in several applications to compare netCDF files.
The `nccmp` [package.py](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/nccmp/package.py) in the authoritative spack repository is not functional.
The `nccmp`  [package.py](https://github.com/NOAA-EMC/spack/blob/jcsda_emc_spack_stack/var/spack/repos/builtin/packages/nccmp/package.py) in this NOAA-EMC fork of spack seems to be the functional.

Can a PR be opened into the authoritative spack repo for `nccmp` so NOAA/NCEP/NCO can fetch and install `nccmp` instead of the fork.  This significantly speeds up processing the installation request.

**Is your feature request related to a problem? Please describe.**
Yes. The `nccmp` recipe in authoritative spack is incomplete. Providing a complete and functional recipe will help getting software installed on operational platforms as well as users elsewhere.

**Describe the solution you'd like**
`nccmp` is complete and functional in the NOAA-EMC fork of spack, but not in the authoritative spack repo.

**Additional context**
This request of installation of `nccmp` is being held up on WCOSS2

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA or @ulmononian Would one of you be able to do this?

**Comment by ulmononian** [comment]
@climbfuji i would be happy to handle this one!

**Comment by climbfuji** [comment]
Thanks very much @ulmononian !

**Comment by ulmononian** [comment]
@aerorahul @climbfuji i put in a super simple pr here https://github.com/spack/spack/pull/35539. please let me know if you would like me to alter the content in any way.

**Comment by aerorahul** [comment]
@ulmononian 
Thanks for the PR.
Just a clarification, I have not tested the `nccmp` install via `spack` specifically.  It is implicitly tested as part of the installs on the various HPCs, containers and platforms.

**Comment by climbfuji** [comment]
FWIW, we've tested it extensively because it's part of all our spack-stack installs since about a year or so.

**Comment by ulmononian** [comment]
@aerorahul & @climbfuji  thanks for the clarification/info. so it has been installed successfully as an environment component on various machines and performs properly in context, then? i can just modify the wording a bit.

**Comment by climbfuji** [comment]
Yes, installed and tested on all the platforms listed here: https://spack-stack.readthedocs.io/en/latest/Platforms.html#pre-configured-sites

**Comment by ulmononian** [comment]
responded to first pass of reviewer comments. i will check that the changes still allow nccmp to install successfully on either hera or orion. will post a note here if/once the PR gets approved & merged.

**Comment by ulmononian** [comment]
@aerorahul when you said: "The nccmp [package.py](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/nccmp/package.py) in the authoritative spack repository is not functional.", i assume you mean that `nccmp` installed using the authoritative version of `package.py`  was not functional when used? i ask because i was able to install it with the [authoritative version](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/nccmp/package.py) without error, but obviously without the same cmake flags in the EMC version.

in any case, it was successfully installed using the [updated version](https://github.com/ulmononian/spack/blob/update_nccmp/var/spack/repos/builtin/packages/nccmp/package.py) of `package.py` here: `/work2/noaa/epic-ps/cbook/spack_nccmp/spack-stack/envs/nccmp_check/install/intel/2022.0.2/nccmp-1.9.0.1-73fkxke`.

**Comment by aerorahul** [comment]
I have not tried with the authoritative repo recipe. 
We usually build NETCDF with MPI and didn't think that would build.

If the recipe from the authoritative repo works for serial NETCDF library, then that's enough, I think.

**Comment by climbfuji** [comment]
I am not aware of any problems when using nccmp built with our spack fork using parallel netcdf4?

**Comment by ulmononian** [comment]
@climbfuji @aerorahul re-requested review over at spack HQ. i added @climbfuji and myself as maintainers as well.

**Comment by climbfuji** [comment]
Closed via https://github.com/spack/spack/pull/35539
