### ISSUE TITLE
Rename jedi-ewok-env to ewok-env

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#527]
**Is your feature request related to a problem? Please describe.**
We have jedi-ufs-env, jedi-mpas-env, jedi-fv3-env, soca-env, and jedi-ewok-env. To me, it makes sense to drop the jedi- from the jedi-ewok-env, because ewok-env doesn't depend on jedi to run (it can be used with just soca-env as well).

**Comment by climbfuji** [comment]
@srherbener Thoughts?

**Comment by srherbener** [comment]
I like the idea to drop "jedi-" from "jedi-ewok-env". Thanks makes it more clear that "ewok-env" isn't a specialized configuration for jedi. 

We probably need "jedi-" prefixes on the other environments that have that "jedi-" prefix since, I believe, those are specialized builds for jedi (with the jedi interfaces for those models). In that vein, why doesn't "soca-env" have the "jedi-" prefix?

**Comment by climbfuji** [comment]
> I like the idea to drop "jedi-" from "jedi-ewok-env". Thanks makes it more clear that "ewok-env" isn't a specialized configuration for jedi.
> 
> We probably need "jedi-" prefixes on the other environments that have that "jedi-" prefix since, I believe, those are specialized builds for jedi (with the jedi interfaces for those models). In that vein, why doesn't "soca-env" have the "jedi-" prefix?

I guess because the applications are called fv3-jedi, mpas-jedi, ..., and soca.
