### ISSUE TITLE
odc@1.4.6 fails to compile on macOS Ventura 13.3.1, Apple M2 Max, using clang@14.0.3

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#585]
**Describe the bug**
odc@1.4.6 fails to compile on macOS Ventura 13.3.1, Apple M2 Max, using clang@14.0.3 in Intel x86_64 emulator mode (Rosetta 2)

Error message is below: https://github.com/JCSDA/spack-stack/issues/585#issuecomment-1551840641

Note that by changing `-O2` to `-O1` allows to manually compile the offending file.

**To Reproduce**
Install odc@1.4.6 on said system

**Expected behavior**
It compiles

**System:**
See above

**Additional context**
n/a

**Comment by smaticka** [comment]
Error Message:

bash-5.2$ cd /Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/build/src/odc && /Users/smaticka/Repos/spack-stack-1.3.1/spack/lib/spack/env/clang/clang++ -Dodccore_EXPORTS -I/Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/build/src -I/Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/src -I/Users/smaticka/Repos/spack-stack-1.3.1/envs/skylab-4.0.0/install/apple-clang/14.0.3/eckit-1.23.0-rkgpax6/include -I/Users/smaticka/Repos/spack-stack-1.3.1/envs/skylab-4.0.0/install/apple-clang/14.0.3/eckit-1.23.0-rkgpax6/include/eckit/sql -I/Users/smaticka/Repos/spack-stack-1.3.1/envs/skylab-4.0.0/install/apple-clang/14.0.3/eckit-1.23.0-rkgpax6/include/eckit -pipe -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-sign-compare -O2 -g -DNDEBUG -std=gnu++11 -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=13.0 -fPIC -MD -MT src/odc/CMakeFiles/odccore.dir/api/odc.cc.o -MF CMakeFiles/odccore.dir/api/odc.cc.o.d -o CMakeFiles/odccore.dir/api/odc.cc.o -c /Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/src/odc/api/odc.cc -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
 "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx13.0.0 -Wundef-prefix=TARGET_OS_ -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name odc.cc -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-strict-return -ffp-contract=on -fno-rounding-math -funwind-tables=2 -target-sdk-version=13.3 -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=lldb -target-linker-version 857.1 -v -fcoverage-compilation-dir=/Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/build/src/odc -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3 -dependency-file CMakeFiles/odccore.dir/api/odc.cc.o.d -skip-unused-modulemap-deps -MT src/odc/CMakeFiles/odccore.dir/api/odc.cc.o -sys-header-deps -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -D odccore_EXPORTS -I /Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/build/src -I /Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/src -I /Users/smaticka/Repos/spack-stack-1.3.1/envs/skylab-4.0.0/install/apple-clang/14.0.3/eckit-1.23.0-rkgpax6/include -I /Users/smaticka/Repos/spack-stack-1.3.1/envs/skylab-4.0.0/install/apple-clang/14.0.3/eckit-1.23.0-rkgpax6/include/eckit/sql -I /Users/smaticka/Repos/spack-stack-1.3.1/envs/skylab-4.0.0/install/apple-clang/14.0.3/eckit-1.23.0-rkgpax6/include/eckit -D NDEBUG -stdlib=libc++ -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -internal-externc-isystem /Library/Developer/CommandLineTools/usr/include -O2 -Wall -Wextra -Wno-unused-parameter -Wno-unused-variable -Wno-sign-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -Wno-reserved-identifier -Wno-gnu-folding-constant -std=gnu++11 -fdeprecated-macro -fdebug-compilation-dir=/Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/build/src/odc -ferror-limit 19 -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fno-cxx-modules -no-opaque-pointers -fcxx-exceptions -fexceptions -fmax-type-align=16 -fcommon -fcolor-diagnostics -vectorize-loops -vectorize-slp -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -clang-vendor-feature=+enableAggressiveVLAFolding -clang-vendor-feature=+revert09abecef7bbf -clang-vendor-feature=+thisNoAlignAttr -clang-vendor-feature=+thisNoNullAttr -mllvm -disable-aligned-alloc-awareness=1 -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/odccore.dir/api/odc.cc.o -x c++ /Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/src/odc/api/odc.cc
clang -cc1 version 14.0.3 (clang-1403.0.22.14.1) default target x86_64-apple-darwin22.4.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/build/src
 /Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/src
 /Users/smaticka/Repos/spack-stack-1.3.1/envs/skylab-4.0.0/install/apple-clang/14.0.3/eckit-1.23.0-rkgpax6/include
 /Users/smaticka/Repos/spack-stack-1.3.1/envs/skylab-4.0.0/install/apple-clang/14.0.3/eckit-1.23.0-rkgpax6/include/eckit/sql
 /Users/smaticka/Repos/spack-stack-1.3.1/envs/skylab-4.0.0/install/apple-clang/14.0.3/eckit-1.23.0-rkgpax6/include/eckit
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1
 /Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
/Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/src/odc/api/odc.cc:343:51: warning: missing field 'propertiesIndex_' initializer [-Wmissing-field-initializers]
        (*frame) = new odc_frame_t {*reader, false};
                                                  ^
/Users/smaticka/Repos/spack-stack-1.3.1/cache/build_stage/spack-stage-odc-1.4.6-buxjb6bcv3rapbegp3j2ukgrniqtjdji/spack-src/src/odc/api/odc.cc:836:88: warning: missing field 'decodedSize' initializer [-Wmissing-field-initializers]
        encoder->columnInfo.emplace_back(ColumnInfo{std::string(name), ColumnType(type)});
                                                                                       ^
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: /var/folders/n2/92s3g12j37x0m0gshqz1q9z8m94b4d/T/odc-06270d.cpp
clang: note: diagnostic msg: /var/folders/n2/92s3g12j37x0m0gshqz1q9z8m94b4d/T/odc-06270d.sh
clang: note: diagnostic msg: Crash backtrace is located in
clang: note: diagnostic msg: /Users/smaticka/Library/Logs/DiagnosticReports/clang_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang: note: diagnostic msg:

**Comment by srherbener** [comment]
I have Ventura 13.3.1 on my Mac as well and I ran into issues like this with the latest Command line tools version (14.3) which contains Clang 14.0.3. I had to back up to command line tools version 14.1 (which contains Clang 14.0.0) to get things working.

You can get a download for 14.1 at https://developer.apple.com/download/all/  Scroll down to the item "Command Line Tools for Xcode 14.1 Release Candidate 2" and proceed. After installing your Clang version should be reverted to 14.0.0. You will need to use your apple id to log onto this site.

My recommendation is to stay on Clang 14.0.0 for now.

**Comment by climbfuji** [comment]
Since changing `-O2` to `-O1` fixes the issue, I am wondering if we should just make this a default for 14.0.3 and be able to use it?

**Comment by srherbener** [comment]
I think it would be good to try and see if we can get Clang 14.0.3 working.

I see using `-O1` optimization as a reasonable workaround (ie, only on the Mac) since we will only be running low resolution experiments.

I'm good with using `-O1` as a default for apple clang 14.0.3 while compiling the odc library.
