### ISSUE TITLE
Support for extra rpaths not supported in setup_metamodules

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#61]
I get this message when I added GCC to `extra_rpaths` in `compilers.yaml`. 

I don't think there's anything that needs to be supported when using extra_rpaths (or just append it to LD_LIBRARY_PATH for the same effect). The extra rpath is embedded into whatever executable/shared library was built with Spack. New executables created from the stack won't have the rpath embedded, but I don't think that matters. If you link to a library that contains the extra_rpath the rpath is already embedded, and everything would still work.

I could use `LD_LIBRARY_PATH` instead. I suppose it doesn't really make a difference as long as you have the meta module loaded.

@climbfuji

**Comment by kgerheiser** [comment]
Since setup_metamodules already handles LD_LIBRARY_PATH I'll just use that.

**Comment by climbfuji** [comment]
The "error" in the meta modules script is simply a guard because I had no use case and no way to test the extra rpath functionality in the compiler section and whether it needs to bleed into the meta modules or not. You can simply remove the guard and see what happens, or we use LD_LIBRARY_PATH because this works fine.

This is how I do all my manual testing: (a) build the stack (b) create the meta modules (c) compile the ufs-weather-model and/or one of the jedi bundles.

**Comment by kgerheiser** [comment]
In practical terms I don't think it really matters. 

With rpath, the library path is embedded in the executable without the need for having LD_LIBRARY_PATH set. To have LD_LIBRARY_PATH set the meta module has to be loaded, which is generally advisable anyway.

If we want to get real fancy we could take the rpath and set `LDFLAGS` to `-Wl,-rpath=<path>`
