### ISSUE TITLE
spack bug (?): concretizer modifying spack.yaml - related: better way to organize site config yamls?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#71]
Beta testers using the "default" site config found that the concretize step can corrupt the spack.yaml file. Specifically, it replaces variables followed by double colons (e.g. `compiler::`) with invalid quotes (`'compiler:':). If the corresponding section that sets the default compiler gets moved into `site.yaml` as it is the case for the pre-configured sites, this does not happen.

I would like to use this issue to revisit how the site configs. It is a bit confusing to me that the common config files are all copied as is, but the site configs get merged into one file. How about the site config files remain separate but are prefixed with `site_`? For example, one would then have:
```
config.yaml
install
modules.yaml
packages.yaml
site_compilers.yaml
site_config.yaml
site_modules.yaml
site_packages.yaml
spack.yaml
```

We would also need instructions how users using the "default" site config would configure it (move `spack external find` stuff from spack.yaml to the various `site_*.yaml` files?) before running the concretizer.

Looking for input and ideas ...

**Comment by kgerheiser** [comment]
Yeah this could be improved. 

The site.yaml is made into one file because you can have multiple optional config files, and I couldn't find an easy way of editing the yaml file directly in Python. Say, one site has a `mirrors.yaml` (would be useful for Hera, for example), then the Spack.yaml needs a way to include that, and you would need to add it to the include somehow. So, it was easier to construct the site.yaml and put the configs in one.

You can have Spack pick up a configuration scope by passing `-C`, but you have to remember to pass that flag each time, and I thought having it integrated was better. It would be nice to automatically have Spack pickup a new configuration scope somehow.

There's also these environment variables like `SPACK_USER_CONFIG_PATH` and `SPACK_SYSTEM_CONFIG_PATH` automatically pick them up, but they have to be set ahead of time.


Or directly include the text into the `spack.yaml` for one integrated environment file. That might be the ideal solution. But you need a way to reconcile a common packages.yaml and a site packages.yaml.

**Comment by kgerheiser** [comment]
I'm going to take a stab at improving this by dynamically including the necessary configs.
