### ISSUE TITLE
add jedi-soca-bundle-env

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA/spack-stack#78]
I think it'd be good to have an option to build https://github.com/JCSDA-internal/soca with spack stack.

I started on trying to build soca (using `jedi-fv3-bundle-env` as a starting point), and here are a few things I discovered:
1. `jedi-soca-bundle-env` will need `nco` (some soca tests use `ncks`)

2. One of the first tests fails with:
>  3: ===============================================================================
3: Running test executable
3: ===============================================================================
3: dyld: Library not loaded: @rpath/libatlas_f.0.27.dylib
3:   Referenced from: /Users/annash/Documents/jedi/build/all-bundle/bin/soca_gridgen.x
3:   Reason: image not found
3: dyld: Library not loaded: @rpath/libatlas_f.0.27.dylib
3:   Referenced from: /Users/annash/Documents/jedi/build/all-bundle/bin/soca_gridgen.x
3:   Reason: image not found

Looks like Fortran `atlas` library isn't found? Any ideas how to fix this?

**Comment by climbfuji** [comment]
@shlyaeva This is still under development, I have an environment that builds soca, tests are next ...

**Comment by shlyaeva** [comment]
@climbfuji oh great, thank you!

**Comment by kgerheiser** [comment]
Hmm, guessing you're running on a Mac? I think rpath is not supported on macOS.


"Control whether Spack embeds RPATH or RUNPATH attributes in ELF binaries so that they can find their dependencies. Has no effect on macOS. Two options are allowed:"

https://spack.readthedocs.io/en/latest/config_yaml.html#shared-linking

I  think we should set DYLD_LIBRARY_PATH in modules.yaml (https://github.com/NOAA-EMC/spack-stack/blob/56acc373505116037e493bb4c4d1863fff0e09b8/configs/common/modules.yaml#L153-L155)

**Comment by shlyaeva** [comment]
> Hmm, guessing you're running on a Mac? I think rpath is not supported on macOS.

Yes, I am! Thank you for looking into it, I'll try with the updated develop!

**Comment by climbfuji** [comment]
> I think it'd be good to have an option to build https://github.com/JCSDA-internal/soca with spack stack.
> 
> I started on trying to build soca (using `jedi-fv3-bundle-env` as a starting point), and here are a few things I discovered:
> 
> 1. `jedi-soca-bundle-env` will need `nco` (some soca tests use `ncks`)
> 2. One of the first tests fails with:
> 
> > 3: ===============================================================================
> > 3: Running test executable
> > 3: ===============================================================================
> > 3: dyld: Library not loaded: @rpath/libatlas_f.0.27.dylib
> > 3:   Referenced from: /Users/annash/Documents/jedi/build/all-bundle/bin/soca_gridgen.x
> > 3:   Reason: image not found
> > 3: dyld: Library not loaded: @rpath/libatlas_f.0.27.dylib
> > 3:   Referenced from: /Users/annash/Documents/jedi/build/all-bundle/bin/soca_gridgen.x
> > 3:   Reason: image not found
> 
> Looks like Fortran `atlas` library isn't found? Any ideas how to fix this?

@shlyaeva I found the problem with the soca tests, it's got nothing to do with the spack stack. @travissluka The soca tests use a wrapper `${CMAKE_CURRENT_SOURCE_DIR}/test_wrapper.sh` to run the executables. The problem with this is that it gets caught by the macOS SIP (System Integration Protection), because it launches the native macOS bash. This  strips essentially everything from the various library search paths.

@srherbener reported this problem first and solved it in really nice way, therefore I take no credit in identifying the problem and solving it. All we need to do is to update the following block of code in soca's `test/CMakeLists.txt`:
```
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index b252a60..569000b 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -348,8 +348,9 @@ function(soca_add_test)
     # run the comapre.py script afterwards
     ecbuild_add_test( TARGET  test_soca_${ARG_NAME}
                       TYPE    SCRIPT
-                      COMMAND "${CMAKE_CURRENT_SOURCE_DIR}/test_wrapper.sh"
-                      ARGS    "${CMAKE_BINARY_DIR}/bin/${ARG_EXE}"
+                      COMMAND bash
+                      ARGS    "${CMAKE_CURRENT_SOURCE_DIR}/test_wrapper.sh"
+                              "${CMAKE_BINARY_DIR}/bin/${ARG_EXE}"
                               ${CONFIG_FILE}
                       ENVIRONMENT
                               ${TRAPFPE_ENV}
```
For macOS, we instruct users to install `bash` from homebrew, which is the first to be found in the search path (`PATH`). This version of bash is not subject to the SIP.  With this simple change, I was able to run `test_soca_gridgen_small`, which failed beforehand with the same error that you reported. @travissluka I am going to submit a PR to soca to fix this.

**Comment by climbfuji** [comment]
SOCA PR https://github.com/JCSDA-internal/soca/pull/727

**Comment by climbfuji** [comment]
@shlyaeva With this change, I got 34/68 tests to pass, 33 failed mostly (or all - not sure) because of the xxxxx Cortex "Advanced" Endpoint Protection. Not sure what's advanced about killing our executables, though.

**Comment by kgerheiser** [comment]
Wow,  that's really good to know about DYLD_LIBRARY_PATH and SIP. I've run into this before and wondered why DYLD_LIBRARY_PATH wasn't working. I've never used a non-system Bash (I guess it's really zsh) before.

**Comment by climbfuji** [comment]
@shlyaeva @travissluka Not all of the soca tests fail because of Cortex, for example:

```
> ctest --output-on-failure -R test_soca_checkpointmodel
...
Running compare script
===============================================================================
Float mismatch at line 8: 34.544390  not equal to  34.544398  with max relative difference  1e-12  Actual relative difference =  2.3158607720478338e-07
Float mismatch at line 9: 6.017574  not equal to  6.019671  with max relative difference  1e-12  Actual relative difference =  0.00034847924620798505
Float mismatch at line 13: 34.539770  not equal to  34.539779  with max relative difference  1e-12  Actual relative difference =  2.6056918575687414e-07
Float mismatch at line 14: 6.017712  not equal to  6.019807  with max relative difference  1e-12  Actual relative difference =  0.0003481389026029882
Failed in the COMPARE step. Error code: 1
```
I don't think that this is a problem with spack-stack, therefore out of scope of this issue.

**Comment by climbfuji** [comment]
Good news @shlyaeva @travissluka. There is a way to avoid Cortex XDR killing our apps. With that, I have 62/86 tests passing, the other six are failing due to float mismatches. This could be because I compiled in `debug` mode, or because I am on an entirely different system (macOS Monterey, llvm-clang@13.0.0 running in rosetta2 emulator mode on an Apple Silicon M1 chip).

Enough for today!
