### ISSUE TITLE
Set up automated nightly builds using Jenkins and Github self-hosted runners

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#840]
**Is your feature request related to a problem? Please describe.**
To reduce the workload when rolling out new releases, let's try the following:

EPIC sets up nightly builds of spack-stack develop one one system using Intel & GNU with Jenkins, JCSDA does the same with a Github self-hosted runner.

- [ ] EPIC: Host **???** with Intel and GNU, Jenkins
- [x] JCSDA: AWS ParallelCluster using a hpc6a.48xlarge head node with Intel and GNU, Github self-hosted runner

**Describe the solution you'd like**
We want to do this as follows:
- Daily builds use the spack binary cache for quick installs, and update the binary cache at the end of the process
- Sunday builds ignore what's in the binary cache and build everything from scratch, then update the existing binary cache

At this time, we want the binary cache be a subdirectory next to the source cache in the `spack-stack` directory on that machine. Any integration with E4S or a super-cache on a shared bucket is future work.

**Additional context**
n/a

**Comment by mark-a-potts** [comment]
I have a Jenkins job set up to build spack-stack on Hercules on a nightly basis. I tested it with Intel on 1.5.0 which completed successfully, 1.5.1, which had an error, and am now trying a build from develop. After each build, I am doing a spack buildcache push so that any new packages are getting added. 

FTR, here is the error I got on 1.5.1--

==> Installing py-et-xmlfile-1.0.1-sclkii3wihuwapd7urj4m5lzbvy7hli5
==> No binary for py-et-xmlfile-1.0.1-sclkii3wihuwapd7urj4m5lzbvy7hli5 found: installing from source
/usr/bin/tar: Relink `/apps/spack-managed/gcc-11.3.1/intel-oneapi-compilers-2023.1.0-sb753366rvywq75zeg4ml5k5c72xgj72/compiler/2023.1.0/linux/compiler/lib/intel64_lin/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `sincosf'
==> Fetching file:///work/noaa/epic/role-epic/spack-stack/source-cache/_source-cache/archive/61/614d9722d572f6246302c4491846d2c393c199cfa4edc9af593437691683335b.tar.gz
==> Error: ProcessError: Command exited with status -11:
    '/usr/bin/tar' '-oxf' '/work2/noaa/epic/role-epic/spack-test/spack-stack/cache/build_stage/spack-stage-py-et-xmlfile-1.0.1-sclkii3wihuwapd7urj4m5lzbvy7hli5/et_xmlfile-1.0.1.tar.gz'
==> Warning: Skipping build of py-openpyxl-3.0.7-b2br7db2tgwvpeuy4mvqfbpoa2m57vps since py-et-xmlfile-1.0.1-sclkii3wihuwapd7urj4m5lzbvy7hli5 failed
==> Warning: Skipping build of py-pandas-1.5.3-qslcbchqje3nqc2jmhdedc4gzo4nkwi4 since py-openpyxl-3.0.7-b2br7db2tgwvpeuy4mvqfbpoa2m57vps failed
==> Warning: Skipping build of jedi-base-env-1.0.0-3bxqu3ibfh7tfpf265faq7x2ii6vhhbr since py-pandas-1.5.3-qslcbchqje3nqc2jmhdedc4gzo4nkwi4 failed
==> Warning: Skipping build of jedi-um-env-1.0.0-lhldbod3of53d624xb327zbnrgkhinky since jedi-base-env-1.0.0-3bxqu3ibfh7tfpf265faq7x2ii6vhhbr failed
==> Warning: Skipping build of jedi-fv3-env-1.0.0-22u27kwxw4vlp7smanv6ppmuilocfraa since jedi-base-env-1.0.0-3bxqu3ibfh7tfpf265faq7x2ii6vhhbr failed
==> Warning: Skipping build of soca-env-1.0.0-iq6zys2azqvsdmma53rx7qm35uufqytm since jedi-base-env-1.0.0-3bxqu3ibfh7tfpf265faq7x2ii6vhhbr failed
==> Warning: Skipping build of jedi-mpas-env-1.0.0-igumymb2wlur5grke53ynsoabrgpc5eg since jedi-base-env-1.0.0-3bxqu3ibfh7tfpf265faq7x2ii6vhhbr failed
==> Warning: Skipping build of ewok-env-1.0.0-rchnnlmjevkstwqdroycvikv7vot5khk since jedi-base-env-1.0.0-3bxqu3ibfh7tfpf265faq7x2ii6vhhbr failed
==> Warning: Skipping build of jedi-ufs-env-1.0.0-ttxpece3vs7sllogzm3exosz3e4niix4 since jedi-base-env-1.0.0-3bxqu3ibfh7tfpf265faq7x2ii6vhhbr failed
==> Warning: Skipping build of jedi-neptune-env-1.0.0-tujh5kdmdyina4hvmihc3hxs7mdncgpw since jedi-base-env-1.0.0-3bxqu3ibfh7tfpf265faq7x2ii6vhhbr failed
==> Warning: Skipping build of ufs-pyenv-1.0.0-f2ypamztxeetwxnmop3bv3hyqiswn5q2 since py-pandas-1.5.3-qslcbchqje3nqc2jmhdedc4gzo4nkwi4 failed
==> Warning: Skipping build of ufs-weather-model-env-1.0.0-t3hcovbhc5tzhiovyhijb4mpgzhokvy4 since ufs-pyenv-1.0.0-f2ypamztxeetwxnmop3bv3hyqiswn5q2 failed
==> Warning: Skipping build of ufs-srw-app-env-1.0.0-ya2qt7iurnan5hg3qyee3murcbdrt42f since ufs-pyenv-1.0.0-f2ypamztxeetwxnmop3bv3hyqiswn5q2 failed
==> Warning: Skipping build of global-workflow-env-1.0.0-amvo5ig46vd7vgdzse4h3p6knbck6h6k since ufs-pyenv-1.0.0-f2ypamztxeetwxnmop3bv3hyqiswn5q2 failed
==> Warning: Skipping build of met-11.1.0-jmav3ehsq7a5bejeujbgqwbso2dd55br since py-pandas-1.5.3-qslcbchqje3nqc2jmhdedc4gzo4nkwi4 failed
==> Warning: Skipping build of metplus-5.1.0-vmaiazrrpadr35owmbt3dtclbrwim7eh since met-11.1.0-jmav3ehsq7a5bejeujbgqwbso2dd55br failed
==> Warning: Skipping build of py-xarray-2022.3.0-wafb7532cikzvvhuwdsp7zxskjwq3jvg since py-pandas-1.5.3-qslcbchqje3nqc2jmhdedc4gzo4nkwi4 failed

**Comment by mark-a-potts** [comment]
Logs with a timestamp from the builds will be placed here--/work2/noaa/epic/role-epic/spack-test
The last attempted build will be in /work2/noaa/epic/role-epic/spack-test/spack-stack

**Comment by climbfuji** [comment]
@mark-a-potts @AlexanderRichert-NOAA So far we've added automated builds to only two platforms (Orion - or Hercules? - @mark-a-potts; and AWS ParallelCluster @climbfuji).

We should continue this effort on develop and consider the progress we've made for release/1.6.0 as complete  (that is, keep issue open and as "in progress" for project "release/1.7.0", but mark as "done" for project "release/1.6.0"). Ok with you?

**Comment by AlexanderRichert-NOAA** [comment]
Thumbs up here. Great to see this coming along!

**Comment by mark-a-potts** [comment]
So, I just checked and this job has been running successfully for the last 2 months and 20 days. Results are available via Jenkins, but that requires (generally) a CAC card to access. Should I set up an email notification of some sort or maybe some other way to report results?

**Comment by mark-a-potts** [comment]
The install and concretize logs are here on Hercules-- /work2/noaa/epic/role-epic/spack-test

**Comment by mark-a-potts** [comment]
And, looking more closely at the install logs, it is clear that while the Jenkins job has been running, not everything is getting installed correctly.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA FYI this is an earlier conversation about EPIC setting up automated nightly builds using Jenkins and GitHub for Orion.
