### ISSUE TITLE
Stack management once initial libraries have been installed

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#90]
We're in a pretty good spot here that libraries build with the chosen compilers on our chosen systems. The current method is good for one-off builds and things like containers where we have a single version of each library.

But once the initial libraries are installed we'll have to maintain them and support multiple compilers (GCC/Intel) and add new versions (e.g. ESMF beta snapshots, new releases).

Some random thoughts follow:

* We should attempt to automate this as much as possible, instead of going to each machine individually. Something like we push a change to a "definitive" spec list, it builds in a test space on each machine which mirrors the dev stack, we test it out, and if that works, we push the change to the dev stack. The test and dev stacks should be identical, except when a new change is added.

* We need to support multiple multiple compilers on the same machine (e.g. GCC/Intel). I was toying with using definitions in Spack environments and came up with a pretty good way to handle it. Example on Jet:

```
  definitions:
  - compilermpi: [intel@2021.5.0^intel-oneapi-mpi@2021.5.1, gcc@9.2.0^openmpi@3.1.4]
  - packages: 
     - nceplibs-bundle
     -  ufs-weather-model-env
   
  specs:
  - matrix:
    - [$packages]
    - [$%compilermpi]
```

This builds each of the specs (`nceplibs-bundle`, `ufs-weather-model-env`) with `intel@2021.5.0^intel-oneapi-mpi@2021.5.1`, and `gcc@9.2.0^openmpi@3.1.4`). And as we go we can add new specs to the `packages` definition. 

One thing to note is that Spack does not support definitions in the `include:` section, only config files. So, I think this should be handled by `create-env.py` to expand the package list.

* We can somehow work `spack.lock` into this scheme. It is created from `spack concretize` and contains the exact concretized environment for exactly reproducible builds on the same system.

* Installed stacks should be version controlled for each machine. Something like committing each `spack.lock` or a master list of specs so that we can reproduce builds for any machine.

* Does it make sense to use the bundle modules? Let's say UFS updates it's ESMF version I don't think that ufs-bundle-env module will update it's version. I have to test this out, but it might be better to disable module generation for them.

**Comment by climbfuji** [comment]
A few comments:
- We are still fixing basic problems such as the py-cffi and py-scipy issues I just created in our spack fork
- I have not yet tried the meta module creation with multiple compilers and MPI libraries
    - The script should loop over all of them, but whether it works as intended is to be seen
- The bundle modules are super useful - just say I want to load ufs-weather-model-env and you get all libraries you need
    - Maybe we can have version numbers for them that pin the versions of the libraries to load?
- Are we always going to extend the existing spack installation? It would be cleaner in my opinion if we kept a separate install tree for every major version of our spack-stack, and install updates (minor versions) and bug fixes (patch versions) in the same tree. Otherwise we'll never be able to get rid of old libraries and/or make significant changes with downstream effects.

**Comment by climbfuji** [comment]
One other question: Are we going to have separate installations for EMC, JCSDA (and EPIC) or can we do something smarter and have one official dev stack per machine with a primary and backup maintainer?

**Comment by climbfuji** [comment]
More thoughts! It would be significantly easier to handle if there was a separate installation (environment) per compiler/mpi combination. Since we are not using the concept of core compilers, the entire stack gets built with the (stack-)compiler and (stack-)mpi provider specified in the config. Thus very little overhead compare to putting everything in one install tree. And less danger of accidentally wiping out software when removing an outdated compiler/mpi combo.

**Comment by climbfuji** [comment]
> More thoughts! It would be significantly easier to handle if there was a separate installation (environment) per compiler/mpi combination. Since we are not using the concept of core compilers, the entire stack gets built with the (stack-)compiler and (stack-)mpi provider specified in the config. Thus very little overhead compare to putting everything in one install tree. And less danger of accidentally wiping out software when removing an outdated compiler/mpi combo.

Or, as a compromise, keep the spack environments separate but install in the same install tree ...

**Comment by kgerheiser** [comment]
I've been thinking about this. 

* I think a separate environment per compiler is a good idea. It's annoying that you can't reuse "core" packages that don't depend on compiler (Python, CMake, etc). Can share an install directory, or not.

* EMC/JCSDA share a stack.

* New versions can go in new location. We can have some sort of major versioning number changes.

* The main holdup I have is handling changing versions. Like updating FMS or an ESMF beta snapshot.

> Maybe we can have version numbers for them that pin the versions of the libraries to load?

I like this idea.

What if we use dates as the version number, like 2022.03.31 for UFS, for example as it just added FMS 2022/ESMF 8.3.0b09? We might need to explicitly list some versions in the bundles, and potentially get rid of the nested `base` envs.


You would have to use `when=`, right? It would be `depends_on(emsf@8.3.0b09, when='2022.03.31)`.

**Comment by climbfuji** [comment]
All great suggestions. Right now, we have pinned versions in `configs/common/packages.yaml`, and in the bundles we only list the names of the packages as dependencies. Moving the version information from `configs/common/packages.yaml` is not ideal, unless we do the same with the variants. But for some packages that are implicit dependencies and for which we need to choose specific versions (e.g. `pythran`), it's better to stay in `configs/common/packages.yaml`. So that's a little messy.

Maybe we could keep all version information in `packages.yaml` and have only a "single" version the env packages that we update. Each commit / tag / release of the code will then have a 1-to-1 relation between the versions of the environments (in the environment's `package.py`) and the versions in `packages.yaml`.

We'd need to check if this still allows us to have different versions of certain packages for the different envs, if so required.

**Comment by climbfuji** [comment]
We now have a good strategy for supporting spack-stack on the various platforms, including a uniform directory structure for the quarterly releases, external packages, source and build caches, as well as build matrices for the compilers supported on each machine. We should update the project charter (https://github.com/NOAA-EMC/spack-stack/blob/develop/project_charter.md) accordingly, but as far as this issue is concerned, it can be considered completed.
