### ISSUE TITLE
spack-stack-1.6.0 release candidate available on Hercules for testing

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#922]
**Is your feature request related to a problem? Please describe.**
A spack-stack-1.6.0 release candidate is available on Hercules for testing.

Follow the usual preamble in https://spack-stack.readthedocs.io/en/release-1.6.0/PreConfiguredSites.html#msu-hercules:
```
module purge
module use /work/noaa/epic/role-epic/spack-stack/hercules/modulefiles
module load ecflow/5.8.4
module load mysql/8.0.31
```
Note that the rest of the documentation is *not* yet updated (still pointing to spack-stack-1.5.1).

`unified-env` for GNU and Intel:
```
/work2/noaa/jcsda/dheinzel/spack-stack-1.6.0-rc1/envs/unified-env/install/modulefiles/Core
```

`gsi-addon-env` for GNU and Intel:
```
/work2/noaa/jcsda/dheinzel/spack-stack-1.6.0-rc1/envs/gsi-addon-env/install/modulefiles/Core
```

**Describe the solution you'd like**

Please test these installations with your applications and provide feedback in this issue. We won't start installing the release until December 26, 2023.

**Additional context**
n/a

**Comment by RatkoVasic-NOAA** [comment]
I'm testing SRW on Hercules.

**Comment by climbfuji** [comment]
> I'm testing SRW on Hercules.

Thank you @RatkoVasic-NOAA !

**Comment by DavidHuber-NOAA** [comment]
I am running regression and unit testing on the GSI and UFS_Utils on Hercules.  With luck, I may be able to do a test of the global workflow tomorrow.

**Comment by DavidHuber-NOAA** [comment]
For the GSI, I am running into a CRTM error:

```
 SpcCoeff_ReadFile(Binary)(FAILURE) : Error reading channel data. input statement requires too much data, unit 10, file /work/noaa/stmp/dhuber/gsi-ss_160/tmpreg_global_4denvar/global_4denvar_loproc_updat/./crtm_coeffs/hirs4_n19.SpcCoeff.bin
 CRTM_SpcCoeff_Load(FAILURE) : Error reading SpcCoeff file #1, ./crtm_coeffs/hirs4_n19.SpcCoeff.bin; Process ID: 39
 CRTM_Init(FAILURE) : Error loading SpcCoeff data; Process ID: 39
 crtm_interface*init_crtm:  ***ERROR*** crtm_init error_status=           3
    TERMINATE PROGRAM EXECUTION
```
The `hirs4_n19.SpcCoef.bin` coefficient file is linked to
`/work2/noaa/jcsda/dheinzel/spack-stack-1.6.0-rc1/envs/unified-env/install/intel/2021.9.0/crtm-fix-2.4.0.1_emc-2os2hw2/fix/hirs4_n19.SpcCoeff.bin`
and that file does exist, so I am not sure what the issue is.  We may need investigative support from CRTM/GSI folks.  Tagging @RussTreadon-NOAA for possible POCs.  Note, Russ, that this is CRTM version 2.4.0.1.

**Comment by climbfuji** [comment]
The crtm@2.4.0.1_emc version was added here: https://github.com/JCSDA/spack-stack/pull/893

Maybe also ask @BenjaminTJohnson and @AlexanderRichert-NOAA, but folks may be on leave already.

**Comment by DavidHuber-NOAA** [comment]
I'm seeing the same error for the `global_4denvar`, `hafs_3denvar`, and `hafs_4denvar` tests.  The `netcdf_fv3_regional` test fails similarly, but for the fix file `hirs4_metop-a.SpcCoeff.bin`.  The other three tests, `rtma`, `rrfs_3denvar`, and `global_enkf`, all pass.

**Comment by RussTreadon-NOAA** [comment]
There are problems with the HIRS CRTM coefficient files.   [Click here](https://github.com/NOAA-EMC/GSI/pull/636#issuecomment-1748729736) to see this comment from Andrew Collard.  His comment references CRTM PR [#42](https://github.com/JCSDA/crtm/pull/42).

**Comment by climbfuji** [comment]
Thanks @RussTreadon-NOAA . Do I read your comment correctly that the spack-stack install can stay as is and that this issue was fixed on the GSI side?

**Comment by RussTreadon-NOAA** [comment]
No, @climbfuji , this issue has not been fixed on the GSI side.  

The operational GSI maintains its own copy of `exglobal_atmos_analysis.sh` in [`release/gfsda.v16`](https://github.com/NOAA-EMC/GSI/tree/release/gfsda.v16).  We [removed HIRS entries](https://github.com/NOAA-EMC/GSI/commit/3fc1ce6f141b380a7ef4f5def0880033c5fca846) from the operational analysis script.    This bypasses the problem.  It does not fix the problem.
 
The develop `exglobal_atmos_analysis.sh` is maintained in the [scripts](https://github.com/NOAA-EMC/global-workflow/tree/develop/scripts) directory of the [g-w](https://github.com/NOAA-EMC/global-workflow) repository.  The develop [`exglobal_atmos_analysis.sh`](https://github.com/NOAA-EMC/global-workflow/blob/develop/scripts/exglobal_atmos_analysis.sh) still contains HIRS entries.  I expect that this script will fail when running with CRTM coefficients taken from crtm/2.4.0.1.

The GSI regression tests do not use `exglobal_atmos_analysis.sh`.  The regression test scripts and namelists reference HIRS for select tests.  Hence, their failing when using crtm/2.4.0.1 coefficients.

It's beneficial to bring @ADCollard into the conversation since he did the work.

**Comment by ADCollard** [comment]
@climbfuji @RussTreadon-NOAA @DavidHuber-NOAA Yes, this is an unfortunate side effect of issues that occurred with CRTM coefficient file versioning over the summer.    Ideally we would have CRTM modify these files to be consistent, but as HIRS is no longer used operationally (and has not been for many years) and given the lack of resources on the CRTM for this the path of least resistance is to not process HIRS at all.

So if I understand the issue correctly, would this be solved by modifying the develop version of [exglobal_atmos_analysis.sh](https://github.com/NOAA-EMC/global-workflow/blob/develop/scripts/exglobal_atmos_analysis.sh) to remove these observations.  Or does it need to be addressed elsewhere?

**Comment by RussTreadon-NOAA** [comment]
Removing HIRS entries from g-w `exglobal_atmos_analysis.sh` will allow global workflow `gsi.x` jobs to run to completion.  The GSI regression test failures require removal of HIRS entries from the regression test scripts and namelists.  So we need two issues - one in [g-w](https://github.com/NOAA-EMC/global-workflow/issues) and another in [GSI](https://github.com/NOAA-EMC/GSI/issues).

**Comment by ADCollard** [comment]
@RussTreadon-NOAA OK I will work on it.

**Comment by RussTreadon-NOAA** [comment]
Thank you @ADCollard !   Feel free to assign me as a reviewer on the [g-w script PR](https://github.com/NOAA-EMC/global-workflow/pulls) and [GSI regression test PR](https://github.com/NOAA-EMC/GSI/pulls).

**Comment by RatkoVasic-NOAA** [comment]
@climbfuji spack-stack-1.6.0 is installed on Hercules
(it took little bit longer, there are ~350 libraries per compiler comparing to previous ~250)
- tested SRW with 1.6.0, it passed fundamental tests on Hercules
- ufs-weather-model needed two changes module_write_restart_netcdf.F90 and module_wrt_grid_comp.F90 (mpp_chksum and mpp_init). Since SRW is using older WM version (Sep 1st), it might have been already fixed in newer WM.

**Comment by DavidHuber-NOAA** [comment]
The UFS_Utils tests were successful, though some minor differences were noted in the cpld_gridgen test at `mx100` resolution.  @deniseworthen confirmed these were not an issue, so that repo is good to go.

**Comment by climbfuji** [comment]
Testing with UFS applications and JEDI applications was successful, we are now rolling out the release.
