### ISSUE TITLE
libaec module missing on Hercules

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#986]
**Describe the bug**
The libaec module file is missing from the Hercules spack-stack v1.6.0 installation.  The library installed, but the module file was never generated.

**To Reproduce**
`find /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/unified-env/install/modulefiles -name "libaec"`

**Expected behavior**
The module file would have been generated with the installation.

**System:**
What system(s) are you running the code on?
Hercules

**Additional context**
Discovered while testing https://github.com/NOAA-EMC/GSI/pull/684, which fails with netCDF errors.

**Comment by climbfuji** [comment]
@DavidHuber-NOAA This is intentional. See https://github.com/JCSDA/spack-stack/blob/08029ed82217ddc6e1e3572a123492cc8ed816b2/configs/common/modules_lmod.yaml#L39 and https://github.com/JCSDA/spack-stack/blob/08029ed82217ddc6e1e3572a123492cc8ed816b2/configs/common/modules_tcl.yaml#L41. We don't produce modules for `libaec` and several other spack packages to keep the list "short" (well, that is probably not the right term for the number of modules a user is presented at the moment).

If the module is indeed needed, we should remove it from the exclude list so that it is available with the next spack-stack release.

On the other hand, we should look at the list of modules generated for `unified-env` and add as many as we can to the exclude list to make this more readable.

**Comment by DavidHuber-NOAA** [comment]
@climbfuji I see now, thanks for the explanation.  This is probably a special case as `libaec` seems to only have been needed for a standalone test build of netcdf.  In general, I don't think it will be needed, but I'd like to finish my netCDF/GSI testing before closing this issue just to be sure.

**Comment by DavidHuber-NOAA** [comment]
This module is not needed by any end application, so I am closing this issue.
